# Generated by Django 5.1.3 on 2024-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('user1_id', 'user2_id'), name='unique_chatroom_pair'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('user2_id', 'user1_id'), name='unique_chatroom_pair_reverse'),
        ),
    ]
